# Generated by Django 4.0.4 on 2022-05-01 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_dec', models.IntegerField()),
                ('value_bin', models.BinaryField()),
                ('value_hex', models.CharField(max_length=25)),
                ('base', models.CharField(choices=[('Bin', 'Binaire'), ('Dec', 'Decimal'), ('Hex', 'Business')], default='Dec', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
