# Generated by Django 4.0.4 on 2022-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converts', '0002_alter_convert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='value_bin',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convert',
            name='value_dec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convert',
            name='value_hex',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
