# Generated by Django 4.0.4 on 2022-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converts', '0003_alter_convert_value_bin_alter_convert_value_dec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert',
            name='base',
            field=models.CharField(choices=[('Bin', 'Binaire'), ('Dec', 'Decimal'), ('Hex', 'Business')], max_length=3),
        ),
    ]
