# Generated by Django 4.0.4 on 2022-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converts', '0005_remove_convert_base_alter_convert_value_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert',
            name='base',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
